### PR TITLE
Sophie m/update youtube overlay pill

### PR DESCRIPTION
**Pull request by sophie-macmillan**
## What are you changing?
This change builds on https://github.com/guardian/csnx/pull/653, which moves the duration pill.
If the video category is Documentary, Explainer or Live it includes this in the pill

## Why?
It wasn't clear what kind of video readers might be about to view

| Change | Screenshot |
|--------|--------|
| Duration only (no change) | image |
| Documentary | image |
| Explainer | image |
| Live | image |
| Live, with no duration | image |

### CODE REVIEW

**Comment by joecowton1** [comment]
@abeddow91 @sophie-macmillan we're experiencing an issue with TS 5.1 and rollup which means the latest releases of source-react-components and source-react-components-development kitchen are broken. 

We've a PR in progress to roll back to TS 4.9.5 which should be merged early next week - if you can hold off merging this until then everything should be working again. Apologies for the hold up!

**Review by joecowton1 — DISMISSED** [review]
@abeddow91 @sophie-macmillan we're experiencing an issue with TS 5.1 and rollup which means the latest releases of source-react-components and source-react-components-development kitchen are broken.

We've a PR in progress to roll back to TS 4.9.5 which should be merged early next week - if you can hold off merging this until then everything should be working again. Apologies for the hold up!

**Review by marjisound — APPROVED** [review]
Looks good 👍

**Comment by joecowton1** [comment]
@sophie-macmillan @abeddow91 the fix I was talking about is now on main, if you pull that into this branch everything should work again

**Pull request merged**
