### PR TITLE
Add linkComponents to eslint settings

### PR DESCRIPTION
**Pull request by bryophyta**
## What are you changing?

Adding `Link` and `LinkButton` to the recommended eslint config for `source-react-components`.

## Why?

The `linkComponents` setting allows eslint rules to identify custom JSX elements which are being used as links.
For instance, adding this setting allows the
[`jsx-no-target-blank`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md) rule to know that it should check both `<Link>` and `<LinkButton>` from Source components.

It felt like it might belong here (rather than in the DCR eslint config) because this is where the components are created and maintained (so the settings could be removed if the API for these components was changed). But I'd be happy to add it to DCR instead if the maintainers of source components would prefer.

### CODE REVIEW

**Review by ob6160 — COMMENTED** [review]
Great idea, seems like a really useful addition.

In terms of giving access to this configuration to users of the @source/react-components package, I'm wondering if this would be better placed in the `eslint-plugin-source-react-components` package: https://github.com/guardian/csnx/blob/main/libs/%40guardian/eslint-plugin-source-react-components/README.md

This is where we distribute rules for people who consume `@guardian/source-react-components`

**Comment by joecowton1** [comment]
> Great idea, seems like a really useful addition.
> 
> In terms of giving access to this configuration for users of the `@guardian/source-react-components` package, I'm wondering if this would be better placed in the `@guardian/eslint-plugin-source-react-components` package: [`main`/libs/%40guardian/eslint-plugin-source-react-components/README.md](https://github.com/guardian/csnx/blob/main/libs/%40guardian/eslint-plugin-source-react-components/README.md?rgh-link-date=2023-02-07T10%3A37%3A39Z)
> 
> This is where we distribute rules for people who consume `@guardian/source-react-components`

Ditto what Ollie says here.

**Comment by bryophyta** [comment]
okay thanks both! I'm pretty new to eslint so that's v helpful. I'll move it and push the change. Do either of you have a sense of what level this change would be? It should be a no-op in terms of the actual code being run, but could cause new errors to be flagged, depending on how the consumer's eslint is configured (e.g. if they do have the `jsx-no-target-blank` rule enabled).

**Comment by ob6160** [comment]
> @ob6160 I've updated the branch following your suggestion. Any guidance on whether this should be considered major/minor/patch would be gratefully received :)

Hmm, I have a feeling that this might come under the "major" category as it adds new functionality that could break peoples' eslint build when they upgrade.

From [the docs(https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md#custom-link-components) it seems as though anyone who is using the `LinkButton` or `Link` component could potentially start to have a new set of errors due to the linter counting those as if they were `<a />` elements. @joecowton1 do you have any thoughts on this too?

I usually go by https://semver.org/ when I'm making decisions, it's very easy to get wrong by accident as the line can be blurry at times :)

**Review by ob6160 — APPROVED** [review]
nice one, thanks for the contribution! 💎

**Comment by bryophyta** [comment]
Thanks for the review @ob6160 !

Just fyi I don't think I have the right permissions to merge in this repo, so someone else might have to do it when you have time, thanks!

**Pull request merged**
