### PR TITLE
Update tslib version

### PR DESCRIPTION
**Pull request by joecowton1**
## What are you changing?

- updating tslib versions across csnx

## Why?

- we were seeing per deps errors

### CODE REVIEW

**Review by mxdvl — COMMENTED** [review]
I'm not sure why a devDependencies update should result in a patch update. I believe it should not release a new version at all.

**Comment by joecowton1** [comment]
> I'm not sure why a devDependencies update should result in a patch update. I believe it should not release a new version at all.

Can you suggest another way to consume the updated packages than via a release?

**Comment by mxdvl** [comment]
> > I'm not sure why a `devDependencies` update should result in a patch update. I believe it should not release a new version at all.
> 
> Can you suggest another way to consume the updated packages than via a release?

I don’t think consumers should be impacted by internal changes of `devDependencies`

**Comment by joecowton1** [comment]
@mxdvl because of the way packages are consumed by one another i still can't think of another way of doing this 😵‍💫 

@sndrs do you have any input on this one?

**Comment by ob6160** [comment]
> I don’t think consumers should be impacted by internal changes of devDependencies, so they should not need to consume it.

I suppose this can be seen both ways. Looking at this through the lens of a consumer, I think I'd impacted by the internal changes here; in that if I didn't receive the updates included in this release I'd experience peer deps errors.

In the interests of not blocking peoples' time and based on my thinking above I'm of the opinion that the patch release is alright to go ahead with. We should discuss in more depth and agree an approach for this to prevent similar future scenarios.

**Review by ob6160 — APPROVED** [review]

**Pull request merged**
